language: node_js
node_js:
  - lts/*

cache:
  directories:
    - "./node_modules"
  yarn: true


branches:
  only:
    - master

install:
  - yarn 

script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - yarn && GIT_USER="${GH_NAME}" yarn deploy

